require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  StyleGuideCopsOnly: true
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false
